apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata: 
      labels:
        app: helloworld
    spec:
      containers:     
        - name: helloworld
          image: netfoundry/hello-world-webpage
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"